package POJOS;
// Generated 4 Mar, 2019 9:25:23 PM by Hibernate Tools 4.3.1



/**
 * Cart generated by hbm2java
 */
public class Cart  implements java.io.Serializable {


     private Integer id;
     private ProductMaster productMaster;
     private String sessionId;
     private Byte productStatus;
     private Byte sessionStatus;

    public Cart() {
    }

    public Cart(ProductMaster productMaster, String sessionId, Byte productStatus, Byte sessionStatus) {
       this.productMaster = productMaster;
       this.sessionId = sessionId;
       this.productStatus = productStatus;
       this.sessionStatus = sessionStatus;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public ProductMaster getProductMaster() {
        return this.productMaster;
    }
    
    public void setProductMaster(ProductMaster productMaster) {
        this.productMaster = productMaster;
    }
    public String getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }
    public Byte getProductStatus() {
        return this.productStatus;
    }
    
    public void setProductStatus(Byte productStatus) {
        this.productStatus = productStatus;
    }
    public Byte getSessionStatus() {
        return this.sessionStatus;
    }
    
    public void setSessionStatus(Byte sessionStatus) {
        this.sessionStatus = sessionStatus;
    }




}


