package POJOS;
// Generated 14 Mar, 2019 10:42:51 AM by Hibernate Tools 4.3.1



/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private Integer id;
     private OrderMaster orderMaster;
     private ProductMaster productMaster;
     private int quantity;

    public Orders() {
    }

	
    public Orders(int quantity) {
        this.quantity = quantity;
    }
    public Orders(OrderMaster orderMaster, ProductMaster productMaster, int quantity) {
       this.orderMaster = orderMaster;
       this.productMaster = productMaster;
       this.quantity = quantity;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public OrderMaster getOrderMaster() {
        return this.orderMaster;
    }
    
    public void setOrderMaster(OrderMaster orderMaster) {
        this.orderMaster = orderMaster;
    }
    public ProductMaster getProductMaster() {
        return this.productMaster;
    }
    
    public void setProductMaster(ProductMaster productMaster) {
        this.productMaster = productMaster;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }




}


