package POJOS;
// Generated Mar 1, 2019 10:06:39 AM by Hibernate Tools 4.3.1



/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private OrdersId id;
     private OrderMaster orderMaster;
     private ProductMaster productMaster;

    public Orders() {
    }

	
    public Orders(OrdersId id) {
        this.id = id;
    }
    public Orders(OrdersId id, OrderMaster orderMaster, ProductMaster productMaster) {
       this.id = id;
       this.orderMaster = orderMaster;
       this.productMaster = productMaster;
    }
   
    public OrdersId getId() {
        return this.id;
    }
    
    public void setId(OrdersId id) {
        this.id = id;
    }
    public OrderMaster getOrderMaster() {
        return this.orderMaster;
    }
    
    public void setOrderMaster(OrderMaster orderMaster) {
        this.orderMaster = orderMaster;
    }
    public ProductMaster getProductMaster() {
        return this.productMaster;
    }
    
    public void setProductMaster(ProductMaster productMaster) {
        this.productMaster = productMaster;
    }




}


