package POJOS;
// Generated 4 Mar, 2019 9:25:23 PM by Hibernate Tools 4.3.1



/**
 * Payment generated by hbm2java
 */
public class Payment  implements java.io.Serializable {


     private Integer id;
     private OrderMaster orderMaster;
     private UserMaster userMaster;
     private Byte paymentStatus;
     private String paymentMode;

    public Payment() {
    }

    public Payment(OrderMaster orderMaster, UserMaster userMaster, Byte paymentStatus, String paymentMode) {
       this.orderMaster = orderMaster;
       this.userMaster = userMaster;
       this.paymentStatus = paymentStatus;
       this.paymentMode = paymentMode;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public OrderMaster getOrderMaster() {
        return this.orderMaster;
    }
    
    public void setOrderMaster(OrderMaster orderMaster) {
        this.orderMaster = orderMaster;
    }
    public UserMaster getUserMaster() {
        return this.userMaster;
    }
    
    public void setUserMaster(UserMaster userMaster) {
        this.userMaster = userMaster;
    }
    public Byte getPaymentStatus() {
        return this.paymentStatus;
    }
    
    public void setPaymentStatus(Byte paymentStatus) {
        this.paymentStatus = paymentStatus;
    }
    public String getPaymentMode() {
        return this.paymentMode;
    }
    
    public void setPaymentMode(String paymentMode) {
        this.paymentMode = paymentMode;
    }




}


