package POJOS;
// Generated 6 Mar, 2019 6:57:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UserMaster generated by hbm2java
 */
public class UserMaster  implements java.io.Serializable {


     private Integer userId;
     private String email;
     private String name;
     private String address;
     private Long contact;
     private Byte category;
     private String password;
     private Set orderMasters = new HashSet(0);
     private Set payments = new HashSet(0);

    public UserMaster() {
    }

	
    public UserMaster(String password) {
        this.password = password;
    }
    public UserMaster(String email, String name, String address, Long contact, Byte category, String password, Set orderMasters, Set payments) {
       this.email = email;
       this.name = name;
       this.address = address;
       this.contact = contact;
       this.category = category;
       this.password = password;
       this.orderMasters = orderMasters;
       this.payments = payments;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Long getContact() {
        return this.contact;
    }
    
    public void setContact(Long contact) {
        this.contact = contact;
    }
    public Byte getCategory() {
        return this.category;
    }
    
    public void setCategory(Byte category) {
        this.category = category;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getOrderMasters() {
        return this.orderMasters;
    }
    
    public void setOrderMasters(Set orderMasters) {
        this.orderMasters = orderMasters;
    }
    public Set getPayments() {
        return this.payments;
    }
    
    public void setPayments(Set payments) {
        this.payments = payments;
    }




}


